# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Thoughts in Motion
subtitle: A personal blog.
email: hello@mauromotion.com
# description: >- # this means to ignore newlines until "baseurl:"
  This is Mauro's personal blog. Motion designer, music lover, overall nerd.
# baseurl: "/thoughts-in-motion" # the subpath of your site, e.g. /blog
url: "https://blog.mauromotion.com"
twitter_username: mauromograph
github_username:  mauromotion
logo: "/assets/images/MauroMotion_logo_v002.png"
github: [metadata]

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mauro" # "air"contrast", "aqua", "dirt", "sunrise", "dark", "default", "neon", "plum", "mint"

plugins:
  # - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name             : "Mauro Di Ianni"
  avatar           : "assets/images/profile_picture.jpg"
  bio              : "Motion designer, music lover, overall nerd."
  location         : "London, UK"
  email            : 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:blog@mauromotion.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mauromotion.com"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mograph.social/@mauro"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mauromograph"

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
