title: "Thoughts in Motion"
subtitle: // a personal website
email: blog@mauromotion.com
description: "This is Mauro's personal website. Motion designer, music lover, overall nerd."
# domain: blog.mauromotion.com
url: https://blog.mauromotion.com
# baseurl: "/thoughts-in-motion"
twitter_username: mauromograph
github_username:  mauromotion
logo: "/assets/images/MauroMotion_logo_v002.png"
github: [metadata]

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mauro" # "air"contrast", "aqua", "dirt", "sunrise", "dark", "default", "neon", "plum", "mint"
search: true

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name             : "Mauro Di Ianni"
  avatar           : "assets/images/profile_picture.jpg"
  bio              : "Motion designer, music lover, overall nerd. Pronouns: he/him."
  location         : "London, UK"
  email            : 
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:blog@mauromotion.com"
    - label: "Portfolio"
      icon: "fab fa-behance-square"
      url: "https://mauromotion.com"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mograph.social/@mauro"
    - label: "Twitter"
      icon: "fab fa-twitter-square"
      url: "https://twitter.com/mauromograph"
    - label: "Reddit"
      icon: "fab fa-reddit"
      url: "https://www.reddit.com/user/mauro_mograph"
    - label: "Last.fm"
      icon: "fab fa-lastfm-square"
      url: "https://www.last.fm/user/madmonk_TM_"
    - label: "Discogs"
      icon: "fas fa-record-vinyl"
      url: "https://www.discogs.com/user/theRealMadmonk"
    
    
include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true

# Collections
collections:
  now:
    output: true
    permalink: /:collection/:path/
    
defaults:
  # _now_archive
  - scope:
      path: ""
      type: now
    values:
      layout: single
      author_profile: false
      share: true
      
category_archive:
  type: liquid
  path: /categories/

footer:
  links:
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mograph.social/@mauro"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mauromograph"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
